#!/usr/bin/python3

import numpy
import math
import scipy.optimize
import matplotlib.pyplot as plt
import os
import glob
import re

import sys
sys.path.insert(1, '.')
sys.path.insert(1, '../../scripts/py')
import graphene002 as graphene
import fit_res003 as fit_res
import f4track

# Theoretical expansion
#A0 = 4/(3*numpy.pi)
#B0 = A0**2 - 1/8.0
#C0 = ...

# Fit of theoretical S function
A0=0.439023879201735
B0=0.045824276758537
C0=-0.00192214696297599

def proc1(fdir, name, t1,t2, dmax=0, vmin=0, plot_uncorr=False, fo=sys.stdout, use_dfi=1, **kwargs):
  print(name, t1,t2, dmax)
  os.makedirs(fdir + name, exist_ok=1)
  t1=graphene.timeconv(t1)
  pref = fdir + "%s/%i"%(name, float(t1))

  def fitfunc(v,df0,v0, Si=0):
    return df0/(1 + A0*(v/v0) + B0*(v/v0)**2 + C0*(v/v0)**3) + df0*Si

  (fig,ax)=plt.subplots(2,2)

  sfunc=None
  for i in range(4):
    data=f4track.get_track(name, t1,t2, sfunc=sfunc, cache=pref, **kwargs, fit_npars=8)
    if plot_uncorr: ax[1].plot(data.vel, data.dF, 'b-')
    ##############
    # fit dF(vel)

    s = data.DD[0]<data.DD[-1] # sweep direction

    # Crop velocity range
    ii = data.vel>vmin

    # Crop drive
    if dmax>0: ii[data.DD>dmax] = 0

    # Select data for fitting, below minimum of dF
    # Should be done after cropping vmin!
    imin=numpy.argmin(data.dF[ii])
    imin=numpy.where(ii)[0][imin]
    if s: ii[imin:] = 0
    else: ii[0:imin+1] = 0

    if data.vel[ii].size<5:
      print ("  skip short dataset: ", name, t1, data.vel[ii].size)
      return -1

    # fit without dFi
    par=[data.dF[ii][0], 0.2]
    err=[0,0]
    res = scipy.optimize.curve_fit(fitfunc, data.vel[ii], data.dF[ii], par, maxfev=10000)
    par = res[0].tolist()

    if use_dfi:
      par.append(+0.05)
      err.append(0)
      # main fit
      res = scipy.optimize.curve_fit(fitfunc, data.vel[ii], data.dF[ii], par, maxfev=10000)
      par = res[0].tolist()
      err = numpy.sqrt(numpy.diag(res[1])).tolist()
    else:
      par.append(0)
      err.append(0)

    def sfunc(v): return fitfunc(v*data.volt2vel, *par)/par[0]

  numpy.savetxt(pref+'.dat',
    numpy.column_stack((data.vel, data.dF, data.F0, data.DD, ii)),
    fmt="%10.6f %10.6f %11.6f %.6e %1d", header="vel[cm/s]  width[Hz], freq[Hz], drive[A], fit")

  print("%s %s %7.3f %.6f %.6f  %.6f %5.2f"%(name, t1, par[0], par[1], par[2], data.field, data.press), file=fo)

  ##############
  # plot data
  fit_res.plot(ax[0,0], ax[0,0], data.sweep, data.fit, npts=200, xlabel="X", ylabel="Y")

  ax[0,0].set_ylabel("volt, Vrms")
  ax[0,0].legend()

  ax[0,1].plot(data.vel, data.dF, 'b.')
  ax[0,1].plot(data.vel[ii], data.dF[ii], 'r.')
  xx=numpy.linspace(0, max(data.vel), 100)
  ax[0,1].plot(xx, fitfunc(xx, *par), 'k-')
  ax[0,1].set_xlim((0,None))
  ax[0,1].set_ylim((0,fitfunc(0, *par)))
  ax[0,1].set_xlabel("velocity, cm/s")
  ax[0,1].set_ylabel("dF, Hz")

  ax[1,0].plot(data.TT-data.TT[0], data.vel, 'b.-')
  ax[1,0].plot(data.TT[ii]-data.TT[0], data.vel[ii], 'r.-')
  ax[1,0].set_xlabel("time, s")
  ax[1,0].set_ylabel("velocity, cm/s")

  ax[1,1].plot(data.DD, data.vel, 'b.-')
  ax[1,1].plot(data.DD[ii], data.vel[ii], 'r.-')
  ax[1,1].set_xlabel("drive, A")
  ax[1,1].set_ylabel("velocity, cm/s")

  plt.gcf().set_size_inches(8, 8)
  plt.savefig(pref+'.png', dpi=100)
  plt.close()
  return 0

######################################################################
if len(sys.argv)!=2:
  raise Exception("Usage: proc1 <tab file> > <res file>")

tab=sys.argv[1]
name=re.match('(.*/)?([^/]+)\.tab$', tab)

if not name:
  raise Exception("can't parse file name: ", tab)

name = name.groups()
if len(name) == 1:
  fdir = "./"
  name = name[0]
elif len(name) == 2:
  fdir = name[0]
  name = name[1]
else: raise Exception("can't parse file name: ", tab)

fi = open(tab)
fo = open(fdir + "%s.res"%(name), 'w')
print("# name, time, delta0[Hz], v0[cm/s], Si, B[T], P[bar] ", file=fo)

vmin=0.1
while line := fi.readline():
  line = line.split('#')[0]
  line = line.split()
  if len(line)<2: continue

  if line[0]=="vmin":
    vmin=float(line[1])
    continue

  (t1,t2) = line[:2]
  if len(line)>2: dmax=float(line[2])
  else: dmax=0
  proc1(fdir, name, t1, t2, dmax=dmax, vmin=vmin, fo=fo)

