#!/usr/bin/python3

import sys
import numpy
import matplotlib.pyplot as plt
sys.path.insert(1, '../../scripts/py')
#sys.path.insert(1, '.')
import res2corr

fn='20230530-05bar-091mT/w1a/1685460893.dat'

(vel, width) = numpy.loadtxt(fn, unpack=1, usecols=(0,1))
width0 = res2corr.res2_delta_to_delta0(vel, width, 'w1a', 5.0, 0.091)

plt.plot(vel, width,  'r*', label='uncorrected')
plt.plot(vel, width0, 'b*', label='corrected')

plt.legend()
plt.gcf().set_size_inches(8, 8)
plt.savefig('test_res2corr.png', dpi=100)
plt.close()
