


p00_%.res3 p00_%.png: .
	./proc3 ../*-00bar-*/$*.res
	mv $*.res3 p00_$*.res3
	mv $*.png  p00_$*.png

p02_%.res3 p02_%.png: .
	./proc3 ../*-02bar-*/$*.res
	mv $*.res3 p02_$*.res3
	mv $*.png  p02_$*.png

p05_%.res3 p05_%.png: .
	./proc3 ../*-05bar-*/$*.res
	mv $*.res3 p05_$*.res3
	mv $*.png  p05_$*.png
